### ISSUE TITLE
Dataset 404

### ISSUE THREAD

**Issue by JACKYLUO1991** [B10532021/Part-Aware_Measurement_for_3D_Pose_Estimation_and_Tracking#2]
Hi, the dataset link shows a 404, is there another link?

**Comment by B10532021** [comment]
Sorry, I think the dataset was closed by the official. But [here](https://drive.google.com/drive/folders/1LJGcP2v0aQDmetnCzO2PiRP1v4jU6sFC) is another link I know that can download Campus and Shelf dataset. It's from [Cross-View Tracking for Multi-Human 3D Pose Estimation at over 100 FPS](https://github.com/longcw/crossview_3d_pose_tracking) Github page.

**Comment by JACKYLUO1991** [comment]
@B10532021 I've only just searched for it too, thanks for your open source work...
