### ISSUE TITLE
Pedestrians are not detected

### ISSUE THREAD

**Issue by JACKYLUO1991** [B10532021/Part-Aware_Measurement_for_3D_Pose_Estimation_and_Tracking#3]
![image](https://user-images.githubusercontent.com/21237742/165273861-2d56d999-3c53-4e72-bab6-439b124f44bf.png)

Hi, I found in my test code that there are always pedestrians not detected, is it a problem with the detector?

**Comment by B10532021** [comment]
Hi, may I asked this condition occurred in which frames? Or whether you finished running all the frames?
Since our method will start detecting an pedestrian while he/she appears in at least two viewpoints so that we can reconstruct the 3D poses, and that's also the timing we start tracing a pedestrian.

**Comment by B10532021** [comment]
This situation might also happen while too many incorrect joints' locations were detected by the detector.

**Comment by JACKYLUO1991** [comment]
@B10532021 Thanks，I know what the problem is.

**Comment by JACKYLUO1991** [comment]
@B10532021 Hi，I would like to observe the results with my own data, any suggestions on matching parameters?

**Comment by B10532021** [comment]
Sorry for the late reply, I've been busy these days. [Here](https://github.com/ivclab/Part-Aware_Measurement_for_3D_Pose_Estimation_and_Tracking/issues/1#issuecomment-907756100) are some tips on setting the configuration.

**Comment by aviralchharia** [comment]
> @B10532021 Thanks，I know what the problem is.

Hi @JACKYLUO1991 Do you remember what was causing this issue and how you fixed the problem? I am getting the same error. Looking forward to hearing from you!
